### ISSUE TITLE
undefined: syscall.Kill when compiling on windows v1.4

### ISSUE THREAD

**Issue by pmaccamp** [bugsnag/bugsnag-go#96]
### Expected behavior
No errors compiling.

### Observed behavior
When compiling on windows 

> vendor\github.com\bugsnag\bugsnag-go\sessions\tracker.go:133:2: undefined: syscall.Kill

### Steps to reproduce
Compile on windows 

### Version
V 1.4.0

### Additional information
From some quick googling looks like syscall.Kill can be replaced with the following to work on windows:
```
p, err := os.FindProcess(os.Getpid())

if err != nil {
	return err
}

return p.Signal(syscall.SIGTERM)
```

**Comment by abdullah2993** [comment]
+1 for this

**Comment by Cawllec** [comment]
Hi @pmaccamp, thanks for flagging this up, we've currently got a fix for this in progress, and will update this thread with more information when able.

**Comment by kapeel-mopkar** [comment]
+ 1 for this issue

**Comment by hsorellana** [comment]
+1

**Comment by koaywenhui** [comment]
Hi @Cawllec , may I know how's this update going on?

**Comment by kinbiko** [comment]
Hi @koaywenhui and others,

Apologies for the delay in sorting this one out, and thanks again for reporting. This should now compile on Windows as of v1.4.1. Please see [the changelog entry](https://github.com/bugsnag/bugsnag-go/blob/master/CHANGELOG.md#141-2019-03-18) for more details, in particular around how interrupt signals may behave differently on Windows.

**Comment by Masterxilo** [comment]
I am using
```
$ go version
go version go1.20.1 linux/amd64
```
running
```
cd ~
echo 'package main ; import "syscall" ; func main() { syscall.Kill(0, syscall.SIGKILL) }' > ./main.go
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o main-windows-amd64.exe ./main.go
```
I still get
```
# command-line-arguments
./main.go:1:57: undefined: syscall.Kill
```
so this problem still exists.
I still get

**Comment by Masterxilo** [comment]
@kinbiko please reopen

**Comment by kinbiko** [comment]
I no longer work at Bugsnag, but looks like I'm able to re-open the issue so I'll do that for you. I'm sure someone from the team will take a look soon.

**Comment by johnkiely1** [comment]
HI @Masterxilo, It would appear your sample program is not using BugSnag and is instead calling `syscall.Kill` directly. 
In this case it appears to be undefined in go’s std lib  This is not something we can help you with.
